trigger:
  branches:
    include:
    - master
    - feature/*
    - refs/tags/mytag
    exclude:
    - test/*
    - refs/tags/yourtag
  paths:
    # must have branches defined to use paths
    # can not exclude and then include path unless going deeper
    include:
    - development/*
    exclude:
    - README.md

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
